### PR TITLE
containers: Remove Docker Apps support

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike Sul <mike.sul@foundries.io>

### CODE REVIEW

**Comment by mike-sul** [comment]
@doanac I verified all key use-cases.

**Comment by doanac** [comment]
Its looking good. I'll take some time this week to pull this into my factory and play with.

**Comment by mike-sul** [comment]
@doanac Did you have a chance to verify it?

**Review by doanac — COMMENTED** [review]
I may be looking at this wrong, but I found this to be unexpected:
~~~
# from https://ci.foundries.io/projects/andy-corp/lmp/builds/154/publish-docker-app/console
$ fioctl targets show -f andy-corp 155
...
DOCKER APP  VERSION
----------  -------
shellhttpd  shellhttpd.dockerapp-152
~~~
Should this have been eliminated with this PR, or do you think that's orthogonal?

**Comment by mike-sul** [comment]
`mike@msul:~$ fioctl targets show -f andy-corp 155
Tags:	
CI:	https://ci.foundries.io/projects/andy-corp/lmp/builds/155/
Source:

TARGET NAME  OSTREE HASH - SHA256
-----------  --------------------
`

**Comment by mike-sul** [comment]
`mike@msul:~$ fioctl targets show -f andy-corp 154
Tags:	master
CI:	https://ci.foundries.io/projects/andy-corp/lmp/builds/154/
Source:
	https://source.foundries.io/factories/andy-corp/lmp-manifest.git/commit/?id=d854dc8dd7c7e0b8c3da275ba0d8406c4608bbbe
	https://source.foundries.io/factories/andy-corp/meta-subscriber-overrides.git/commit/?id=aa56acfcc315dadec9504ea48e59b92fc7114df9
	https://source.foundries.io/factories/andy-corp/containers.git/commit/?id=0cb0fd6465b0686452b1ccf5bbffffeacf9d555e

TARGET NAME              OSTREE HASH - SHA256
-----------              --------------------
intel-corei7-64-lmp-154  4298bf9926c2204d74eccdbc42d8787bf941def8e144dde71d9e0acd47a8f7f0
raspberrypi3-64-lmp-154  a7de7c13bf29921ef9956b23b96e09048e28e3915f32cc7a60de70e4664c5956

DOCKER APP  VERSION
----------  -------
shellhttpd  shellhttpd.dockerapp-152

COMPOSE APP    VERSION
-----------    -------
helloworld     hub.foundries.io/andy-corp/helloworld@sha256:d09c02b88efc0e6e10ba21568e6ba79a00db3f76116809f90c49009391c31efb
fiotest        hub.foundries.io/andy-corp/fiotest@sha256:c0ca34e48aa35e26fd5090a2d4c6fd4f003f5298f305add0acd49adb4552b0b6
homelab        hub.foundries.io/andy-corp/homelab@sha256:c5d8dab998ad15b037c33781c1217bf4ef0775d40f00b69b9e5cc1a72086bb82
homeassistant  hub.foundries.io/andy-corp/homeassistant@sha256:d39e07d9d6b75ab8b3f56108172cecab02548b0c8352e6d3275ed732dc9dc6cb
`

**Comment by mike-sul** [comment]
`fioctl targets show -f andy-corp 155` There is no build #155 in your factory, but I think Target #154 shouldn't include any docker apps.

**Comment by mike-sul** [comment]
The latest commit to this PR should fix the issue.
This is the job triggered before the commit was made https://ci.foundries.io/projects/andy-corp/lmp/builds/155/ and this is the job after the commit was made https://ci.foundries.io/projects/andy-corp/lmp/builds/156/.
`fioctl targets show -f andy-corp 156` does not yield any docker apps

**Comment by mike-sul** [comment]
I think a potential issue is that customers can expect that their docker apps will be automatically converted into compose apps while the given PR just ignores them. I assume removing  docker apps support implies removing the conversion functionality too and we just inform customers about it and help them to migrate their Docker Apps to Compose Apps?

**Pull request merged**
