### PR TITLE
Test webhook

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by mike-sul** [comment]
Should go after https://github.com/foundriesio/ci-scripts/pull/86.
This is just an initial step/skeleton, going to add some more tests over time.

**Comment by mike-sul** [comment]
@doanac What do you think about this initial step towards setting up some CI for this repo?

**Review by doanac — COMMENTED** [review]
seems fine. but do we want both github action and jobserv in this? I think one or the other would be fine?

**Comment by mike-sul** [comment]
> seems fine. but do we want both github action and jobserv in this? I think one or the other would be fine?

I thought about splitting the overall testing effort between them so we don't use JobServ's worker machines much as they used by our customers. Also, sometimes our worker pool so busy that it takes ages until some worker becomes available for the given tests. But, I don't have a strong opinion, can remove the github's actions.

The next step would be running some high-level/integration tests and it will require setting up some test factory as we discussed earlier.

**Review by doanac — APPROVED** [review]

**Pull request merged**
