### PR TITLE
factory-containers: Add support for advanced tagging

### PR DESCRIPTION
**Pull request by doanac**
Addresses bug #44

### CODE REVIEW

**Comment by doanac** [comment]
I'm testing in my factory right now.

**Comment by doanac** [comment]
I've just done a bunch of permutations and I think this is good-to-go. I'm going to start working on documentation now.

**Comment by EmbeddedAndroid** [comment]
Going to try this out now.

**Comment by EmbeddedAndroid** [comment]
Results are in, after a platform and then a container build, I've got docker-app targets once again.

**Pull request merged**
