### PR TITLE
lmp: bb-config: Fix GPLv3 tags to match SPDX

### PR DESCRIPTION
**Pull request by angolini**
Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>

### CODE REVIEW

**Comment by angolini** [comment]
I have tested this PR with current `meta-lmp/main` and with https://github.com/foundriesio/meta-lmp/pull/589
Both worked as expected:
When `DISABLE_GPLV3=1`, there is a build error showing the packages under a gplv3* license, and when `DISABLE_GPLV3=0`, no error

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
