### PR TITLE
Disable docker build with file

### PR DESCRIPTION
**Pull request by gwendolynbrook**
Modify main loop build script to disable docker builds for directories that aren't meant to be images.

### CODE REVIEW

**Comment by mike-scott** [comment]
@gwendolynbrook We should have @doanac take a look, but we probably want to squash the 2 commits into 1.

From a functionality point of view this looks good tho.

**Comment by doanac** [comment]
I've been toying with something similar that we are about to merge into master:

 https://github.com/foundriesio/ci-scripts/commit/c1815b7544a8536dd9f756173df0dba0c107b05e

This change is doing:
~~~
IMAGES=$(find ./ -mindepth 2 -maxdepth 2 -name Dockerfile | cut -d / -f2)
~~~

Would that work for you? Or are you wanting to put .disable on directories that have a Dockerfile?

**Comment by gwendolynbrook** [comment]
> IMAGES=$(find ./ -mindepth 2 -maxdepth 2 -name Dockerfile | cut -d / -f2)

@doanac this would cover my current need; I don't presently have a case where there's a directory I want to disable that *does* have a dockerfile.

**Comment by doanac** [comment]
I've just merge: https://github.com/foundriesio/ci-scripts/pull/62

**Pull request closed without merging**
