### PR TITLE
apps: remove the ostree-based apps usage

### PR DESCRIPTION
**Pull request by mike-sul**
Remove usage of the ostree-based Apps from the following use-cases:
 - Apps preloading/image assembling.
 - Apps publishing.

Signed-off-by: Mike Sul <mike.sul@foundries.io>

### CODE REVIEW

**Review by doanac — APPROVED** [review]

**Comment by mike-sul** [comment]
@doanac Do you think it makes sense to remove actual "ostree for apps" implementation, I mean this https://github.com/foundriesio/ci-scripts/blob/master/apps/ostree_store.py ?

**Comment by doanac** [comment]
yes - please remove. we can always use git to restore some logic if we find a need

**Comment by mike-sul** [comment]
> yes - please remove

Removed all "ostree for apps" related code.

**Review by doanac — APPROVED** [review]
```
+44 −740
```
That's all i need to see for a +1

**Comment by mike-sul** [comment]
> That's all i need to see for a +1

Let's remove even more code :)

**Pull request merged**
