### PR TITLE
apps: Use the golang compose CLI tool

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike <mike.sul@foundries.io>

### CODE REVIEW

**Review by doanac — APPROVED** [review]
is there an easy way to test this in our factories before pushing to everyone?

**Comment by mike-sul** [comment]
> is there an easy way to test this in our factories before pushing to everyone?

Isn't better if it fails at this stage then later on a device which already running `docker compose` anyway?

**Comment by mike-sul** [comment]
I'll re-run the unit tests once the new image (lmp-image-tools) is built

**Comment by mike-sul** [comment]
I can enable it my factory just to double check.

**Comment by doanac** [comment]
> Isn't better if it fails at this stage then later on a device which already running docker compose anyway?

Wasn't talking about devices. I meant - we can test it in CI a bit to make sure we aren't breaking customer ci unexpectedly. looks like its easy to test it, so no big concern

**Pull request merged**
